[2023-04-28T23:38:51.358+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: booking_ingestion_DAG.load_data manual__2023-04-28T23:38:45.088354+00:00 [queued]>
[2023-04-28T23:38:51.370+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: booking_ingestion_DAG.load_data manual__2023-04-28T23:38:45.088354+00:00 [queued]>
[2023-04-28T23:38:51.371+0000] {taskinstance.py:1288} INFO - 
--------------------------------------------------------------------------------
[2023-04-28T23:38:51.372+0000] {taskinstance.py:1289} INFO - Starting attempt 1 of 1
[2023-04-28T23:38:51.373+0000] {taskinstance.py:1290} INFO - 
--------------------------------------------------------------------------------
[2023-04-28T23:38:51.393+0000] {taskinstance.py:1309} INFO - Executing <Task(PythonOperator): load_data> on 2023-04-28 23:38:45.088354+00:00
[2023-04-28T23:38:51.399+0000] {standard_task_runner.py:55} INFO - Started process 7709 to run task
[2023-04-28T23:38:51.403+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'booking_ingestion_DAG', 'load_data', 'manual__2023-04-28T23:38:45.088354+00:00', '--job-id', '65', '--raw', '--subdir', 'DAGS_FOLDER/main.py', '--cfg-path', '/tmp/tmprvoo_lce']
[2023-04-28T23:38:51.405+0000] {standard_task_runner.py:83} INFO - Job 65: Subtask load_data
[2023-04-28T23:38:51.478+0000] {task_command.py:389} INFO - Running <TaskInstance: booking_ingestion_DAG.load_data manual__2023-04-28T23:38:45.088354+00:00 [running]> on host 0e14e6a5e88f
[2023-04-28T23:38:51.696+0000] {taskinstance.py:1518} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=booking_ingestion_DAG
AIRFLOW_CTX_TASK_ID=load_data
AIRFLOW_CTX_EXECUTION_DATE=2023-04-28T23:38:45.088354+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-04-28T23:38:45.088354+00:00
[2023-04-28T23:38:51.724+0000] {taskinstance.py:1776} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/main.py", line 85, in load_data
    client = MongoClient(host='localhost', port=27017)
NameError: name 'MongoClient' is not defined
[2023-04-28T23:38:51.736+0000] {taskinstance.py:1332} INFO - Marking task as FAILED. dag_id=booking_ingestion_DAG, task_id=load_data, execution_date=20230428T233845, start_date=20230428T233851, end_date=20230428T233851
[2023-04-28T23:38:51.752+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 65 for task load_data (name 'MongoClient' is not defined; 7709)
[2023-04-28T23:38:51.777+0000] {local_task_job.py:212} INFO - Task exited with return code 1
[2023-04-28T23:38:51.801+0000] {taskinstance.py:2596} INFO - 0 downstream tasks scheduled from follow-on schedule check
