[2023-04-28T22:00:14.495+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: booking_ingestion_DAG.transform_data manual__2023-04-28T22:00:10.764960+00:00 [queued]>
[2023-04-28T22:00:14.510+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: booking_ingestion_DAG.transform_data manual__2023-04-28T22:00:10.764960+00:00 [queued]>
[2023-04-28T22:00:14.510+0000] {taskinstance.py:1288} INFO - 
--------------------------------------------------------------------------------
[2023-04-28T22:00:14.511+0000] {taskinstance.py:1289} INFO - Starting attempt 1 of 1
[2023-04-28T22:00:14.512+0000] {taskinstance.py:1290} INFO - 
--------------------------------------------------------------------------------
[2023-04-28T22:00:14.531+0000] {taskinstance.py:1309} INFO - Executing <Task(PythonOperator): transform_data> on 2023-04-28 22:00:10.764960+00:00
[2023-04-28T22:00:14.535+0000] {standard_task_runner.py:55} INFO - Started process 5047 to run task
[2023-04-28T22:00:14.539+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'booking_ingestion_DAG', 'transform_data', 'manual__2023-04-28T22:00:10.764960+00:00', '--job-id', '56', '--raw', '--subdir', 'DAGS_FOLDER/main.py', '--cfg-path', '/tmp/tmpjse5r69n']
[2023-04-28T22:00:14.541+0000] {standard_task_runner.py:83} INFO - Job 56: Subtask transform_data
[2023-04-28T22:00:14.727+0000] {task_command.py:389} INFO - Running <TaskInstance: booking_ingestion_DAG.transform_data manual__2023-04-28T22:00:10.764960+00:00 [running]> on host 0e14e6a5e88f
[2023-04-28T22:00:15.046+0000] {taskinstance.py:1518} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=booking_ingestion_DAG
AIRFLOW_CTX_TASK_ID=transform_data
AIRFLOW_CTX_EXECUTION_DATE=2023-04-28T22:00:10.764960+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-04-28T22:00:10.764960+00:00
[2023-04-28T22:00:15.048+0000] {logging_mixin.py:137} INFO - ready for transform
[2023-04-28T22:00:15.060+0000] {taskinstance.py:1776} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/main.py", line 37, in transform_data
    booking = context['ti'].xcom_pull(key='my_data_1')
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 75, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 2375, in xcom_pull
    return XCom.deserialize_value(first)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/xcom.py", line 661, in deserialize_value
    return BaseXCom._deserialize_value(result, False)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/xcom.py", line 654, in _deserialize_value
    return json.loads(result.value.decode("UTF-8"), cls=XComDecoder, object_hook=object_hook)
  File "/usr/local/lib/python3.7/json/__init__.py", line 361, in loads
    return cls(**kw).decode(s)
  File "/usr/local/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.7/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/json.py", line 215, in object_hook
    raise ImportError(f"{classname} was not found in allow list for import")
ImportError: unusual_prefix_8f3fa82684731fec338e7a38d6fbf711ac450beb_main.PickleableDataFrame was not found in allow list for import
[2023-04-28T22:00:15.104+0000] {taskinstance.py:1332} INFO - Marking task as FAILED. dag_id=booking_ingestion_DAG, task_id=transform_data, execution_date=20230428T220010, start_date=20230428T220014, end_date=20230428T220015
[2023-04-28T22:00:15.164+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 56 for task transform_data (unusual_prefix_8f3fa82684731fec338e7a38d6fbf711ac450beb_main.PickleableDataFrame was not found in allow list for import; 5047)
[2023-04-28T22:00:15.194+0000] {local_task_job.py:212} INFO - Task exited with return code 1
[2023-04-28T22:00:15.256+0000] {taskinstance.py:2596} INFO - 0 downstream tasks scheduled from follow-on schedule check
